package com.zzj.vo;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HomeList.proto

public final class HomeListOuterClass {
  private HomeListOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HomeListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HomeList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .content array = 1;</code>
     */
    java.util.List<content>
        getArrayList();
    /**
     * <code>repeated .content array = 1;</code>
     */
    content getArray(int index);
    /**
     * <code>repeated .content array = 1;</code>
     */
    int getArrayCount();
    /**
     * <code>repeated .content array = 1;</code>
     */
    java.util.List<? extends contentOrBuilder>
        getArrayOrBuilderList();
    /**
     * <code>repeated .content array = 1;</code>
     */
    contentOrBuilder getArrayOrBuilder(
        int index);

    /**
     * <code>int32 page = 2;</code>
     * @return The page.
     */
    int getPage();

    /**
     * <code>int32 totalPage = 3;</code>
     * @return The totalPage.
     */
    int getTotalPage();
  }
  /**
   * Protobuf type {@code HomeList}
   */
  public static final class HomeList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HomeList)
      HomeListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HomeList.newBuilder() to construct.
    private HomeList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HomeList() {
      array_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new HomeList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HomeList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                array_ = new java.util.ArrayList<content>();
                mutable_bitField0_ |= 0x00000001;
              }
              array_.add(
                  input.readMessage(content.parser(), extensionRegistry));
              break;
            }
            case 16: {

              page_ = input.readInt32();
              break;
            }
            case 24: {

              totalPage_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          array_ = java.util.Collections.unmodifiableList(array_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HomeListOuterClass.internal_static_HomeList_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HomeListOuterClass.internal_static_HomeList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              HomeList.class, Builder.class);
    }

    public static final int ARRAY_FIELD_NUMBER = 1;
    private java.util.List<content> array_;
    /**
     * <code>repeated .content array = 1;</code>
     */
    @Override
    public java.util.List<content> getArrayList() {
      return array_;
    }
    /**
     * <code>repeated .content array = 1;</code>
     */
    @Override
    public java.util.List<? extends contentOrBuilder>
        getArrayOrBuilderList() {
      return array_;
    }
    /**
     * <code>repeated .content array = 1;</code>
     */
    @Override
    public int getArrayCount() {
      return array_.size();
    }
    /**
     * <code>repeated .content array = 1;</code>
     */
    @Override
    public content getArray(int index) {
      return array_.get(index);
    }
    /**
     * <code>repeated .content array = 1;</code>
     */
    @Override
    public contentOrBuilder getArrayOrBuilder(
        int index) {
      return array_.get(index);
    }

    public static final int PAGE_FIELD_NUMBER = 2;
    private int page_;
    /**
     * <code>int32 page = 2;</code>
     * @return The page.
     */
    @Override
    public int getPage() {
      return page_;
    }

    public static final int TOTALPAGE_FIELD_NUMBER = 3;
    private int totalPage_;
    /**
     * <code>int32 totalPage = 3;</code>
     * @return The totalPage.
     */
    @Override
    public int getTotalPage() {
      return totalPage_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < array_.size(); i++) {
        output.writeMessage(1, array_.get(i));
      }
      if (page_ != 0) {
        output.writeInt32(2, page_);
      }
      if (totalPage_ != 0) {
        output.writeInt32(3, totalPage_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < array_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, array_.get(i));
      }
      if (page_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, page_);
      }
      if (totalPage_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, totalPage_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof HomeList)) {
        return super.equals(obj);
      }
      HomeList other = (HomeList) obj;

      if (!getArrayList()
          .equals(other.getArrayList())) return false;
      if (getPage()
          != other.getPage()) return false;
      if (getTotalPage()
          != other.getTotalPage()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getArrayCount() > 0) {
        hash = (37 * hash) + ARRAY_FIELD_NUMBER;
        hash = (53 * hash) + getArrayList().hashCode();
      }
      hash = (37 * hash) + PAGE_FIELD_NUMBER;
      hash = (53 * hash) + getPage();
      hash = (37 * hash) + TOTALPAGE_FIELD_NUMBER;
      hash = (53 * hash) + getTotalPage();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static HomeList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HomeList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HomeList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HomeList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HomeList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HomeList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HomeList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static HomeList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static HomeList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static HomeList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static HomeList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static HomeList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(HomeList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HomeList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HomeList)
        HomeListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HomeListOuterClass.internal_static_HomeList_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HomeListOuterClass.internal_static_HomeList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                HomeList.class, Builder.class);
      }

      // Construct using HomeListOuterClass.HomeList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getArrayFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (arrayBuilder_ == null) {
          array_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          arrayBuilder_.clear();
        }
        page_ = 0;

        totalPage_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HomeListOuterClass.internal_static_HomeList_descriptor;
      }

      @Override
      public HomeList getDefaultInstanceForType() {
        return HomeList.getDefaultInstance();
      }

      @Override
      public HomeList build() {
        HomeList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public HomeList buildPartial() {
        HomeList result = new HomeList(this);
        int from_bitField0_ = bitField0_;
        if (arrayBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            array_ = java.util.Collections.unmodifiableList(array_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.array_ = array_;
        } else {
          result.array_ = arrayBuilder_.build();
        }
        result.page_ = page_;
        result.totalPage_ = totalPage_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof HomeList) {
          return mergeFrom((HomeList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(HomeList other) {
        if (other == HomeList.getDefaultInstance()) return this;
        if (arrayBuilder_ == null) {
          if (!other.array_.isEmpty()) {
            if (array_.isEmpty()) {
              array_ = other.array_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureArrayIsMutable();
              array_.addAll(other.array_);
            }
            onChanged();
          }
        } else {
          if (!other.array_.isEmpty()) {
            if (arrayBuilder_.isEmpty()) {
              arrayBuilder_.dispose();
              arrayBuilder_ = null;
              array_ = other.array_;
              bitField0_ = (bitField0_ & ~0x00000001);
              arrayBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getArrayFieldBuilder() : null;
            } else {
              arrayBuilder_.addAllMessages(other.array_);
            }
          }
        }
        if (other.getPage() != 0) {
          setPage(other.getPage());
        }
        if (other.getTotalPage() != 0) {
          setTotalPage(other.getTotalPage());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        HomeList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (HomeList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<content> array_ =
        java.util.Collections.emptyList();
      private void ensureArrayIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          array_ = new java.util.ArrayList<content>(array_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          content, content.Builder, contentOrBuilder> arrayBuilder_;

      /**
       * <code>repeated .content array = 1;</code>
       */
      public java.util.List<content> getArrayList() {
        if (arrayBuilder_ == null) {
          return java.util.Collections.unmodifiableList(array_);
        } else {
          return arrayBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .content array = 1;</code>
       */
      public int getArrayCount() {
        if (arrayBuilder_ == null) {
          return array_.size();
        } else {
          return arrayBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .content array = 1;</code>
       */
      public content getArray(int index) {
        if (arrayBuilder_ == null) {
          return array_.get(index);
        } else {
          return arrayBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .content array = 1;</code>
       */
      public Builder setArray(
          int index, content value) {
        if (arrayBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArrayIsMutable();
          array_.set(index, value);
          onChanged();
        } else {
          arrayBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .content array = 1;</code>
       */
      public Builder setArray(
          int index, content.Builder builderForValue) {
        if (arrayBuilder_ == null) {
          ensureArrayIsMutable();
          array_.set(index, builderForValue.build());
          onChanged();
        } else {
          arrayBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .content array = 1;</code>
       */
      public Builder addArray(content value) {
        if (arrayBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArrayIsMutable();
          array_.add(value);
          onChanged();
        } else {
          arrayBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .content array = 1;</code>
       */
      public Builder addArray(
          int index, content value) {
        if (arrayBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArrayIsMutable();
          array_.add(index, value);
          onChanged();
        } else {
          arrayBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .content array = 1;</code>
       */
      public Builder addArray(
          content.Builder builderForValue) {
        if (arrayBuilder_ == null) {
          ensureArrayIsMutable();
          array_.add(builderForValue.build());
          onChanged();
        } else {
          arrayBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .content array = 1;</code>
       */
      public Builder addArray(
          int index, content.Builder builderForValue) {
        if (arrayBuilder_ == null) {
          ensureArrayIsMutable();
          array_.add(index, builderForValue.build());
          onChanged();
        } else {
          arrayBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .content array = 1;</code>
       */
      public Builder addAllArray(
          Iterable<? extends content> values) {
        if (arrayBuilder_ == null) {
          ensureArrayIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, array_);
          onChanged();
        } else {
          arrayBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .content array = 1;</code>
       */
      public Builder clearArray() {
        if (arrayBuilder_ == null) {
          array_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          arrayBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .content array = 1;</code>
       */
      public Builder removeArray(int index) {
        if (arrayBuilder_ == null) {
          ensureArrayIsMutable();
          array_.remove(index);
          onChanged();
        } else {
          arrayBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .content array = 1;</code>
       */
      public content.Builder getArrayBuilder(
          int index) {
        return getArrayFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .content array = 1;</code>
       */
      public contentOrBuilder getArrayOrBuilder(
          int index) {
        if (arrayBuilder_ == null) {
          return array_.get(index);  } else {
          return arrayBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .content array = 1;</code>
       */
      public java.util.List<? extends contentOrBuilder>
           getArrayOrBuilderList() {
        if (arrayBuilder_ != null) {
          return arrayBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(array_);
        }
      }
      /**
       * <code>repeated .content array = 1;</code>
       */
      public content.Builder addArrayBuilder() {
        return getArrayFieldBuilder().addBuilder(
            content.getDefaultInstance());
      }
      /**
       * <code>repeated .content array = 1;</code>
       */
      public content.Builder addArrayBuilder(
          int index) {
        return getArrayFieldBuilder().addBuilder(
            index, content.getDefaultInstance());
      }
      /**
       * <code>repeated .content array = 1;</code>
       */
      public java.util.List<content.Builder>
           getArrayBuilderList() {
        return getArrayFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          content, content.Builder, contentOrBuilder>
          getArrayFieldBuilder() {
        if (arrayBuilder_ == null) {
          arrayBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              content, content.Builder, contentOrBuilder>(
                  array_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          array_ = null;
        }
        return arrayBuilder_;
      }

      private int page_ ;
      /**
       * <code>int32 page = 2;</code>
       * @return The page.
       */
      @Override
      public int getPage() {
        return page_;
      }
      /**
       * <code>int32 page = 2;</code>
       * @param value The page to set.
       * @return This builder for chaining.
       */
      public Builder setPage(int value) {
        
        page_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 page = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPage() {
        
        page_ = 0;
        onChanged();
        return this;
      }

      private int totalPage_ ;
      /**
       * <code>int32 totalPage = 3;</code>
       * @return The totalPage.
       */
      @Override
      public int getTotalPage() {
        return totalPage_;
      }
      /**
       * <code>int32 totalPage = 3;</code>
       * @param value The totalPage to set.
       * @return This builder for chaining.
       */
      public Builder setTotalPage(int value) {
        
        totalPage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 totalPage = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTotalPage() {
        
        totalPage_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HomeList)
    }

    // @@protoc_insertion_point(class_scope:HomeList)
    private static final HomeList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new HomeList();
    }

    public static HomeList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HomeList>
        PARSER = new com.google.protobuf.AbstractParser<HomeList>() {
      @Override
      public HomeList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HomeList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HomeList> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<HomeList> getParserForType() {
      return PARSER;
    }

    @Override
    public HomeList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface contentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:content)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>string titleImage = 2;</code>
     * @return The titleImage.
     */
    String getTitleImage();
    /**
     * <code>string titleImage = 2;</code>
     * @return The bytes for titleImage.
     */
    com.google.protobuf.ByteString
        getTitleImageBytes();

    /**
     * <code>string day = 3;</code>
     * @return The day.
     */
    String getDay();
    /**
     * <code>string day = 3;</code>
     * @return The bytes for day.
     */
    com.google.protobuf.ByteString
        getDayBytes();

    /**
     * <code>string month = 4;</code>
     * @return The month.
     */
    String getMonth();
    /**
     * <code>string month = 4;</code>
     * @return The bytes for month.
     */
    com.google.protobuf.ByteString
        getMonthBytes();

    /**
     * <code>string year = 5;</code>
     * @return The year.
     */
    String getYear();
    /**
     * <code>string year = 5;</code>
     * @return The bytes for year.
     */
    com.google.protobuf.ByteString
        getYearBytes();

    /**
     * <code>string author = 6;</code>
     * @return The author.
     */
    String getAuthor();
    /**
     * <code>string author = 6;</code>
     * @return The bytes for author.
     */
    com.google.protobuf.ByteString
        getAuthorBytes();

    /**
     * <code>string title = 7;</code>
     * @return The title.
     */
    String getTitle();
    /**
     * <code>string title = 7;</code>
     * @return The bytes for title.
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>string summary = 8;</code>
     * @return The summary.
     */
    String getSummary();
    /**
     * <code>string summary = 8;</code>
     * @return The bytes for summary.
     */
    com.google.protobuf.ByteString
        getSummaryBytes();

    /**
     * <code>string mainTag = 9;</code>
     * @return The mainTag.
     */
    String getMainTag();
    /**
     * <code>string mainTag = 9;</code>
     * @return The bytes for mainTag.
     */
    com.google.protobuf.ByteString
        getMainTagBytes();

    /**
     * <code>int32 love = 10;</code>
     * @return The love.
     */
    int getLove();

    /**
     * <code>int32 commentNum = 11;</code>
     * @return The commentNum.
     */
    int getCommentNum();
  }
  /**
   * Protobuf type {@code content}
   */
  public static final class content extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:content)
      contentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use content.newBuilder() to construct.
    private content(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private content() {
      titleImage_ = "";
      day_ = "";
      month_ = "";
      year_ = "";
      author_ = "";
      title_ = "";
      summary_ = "";
      mainTag_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new content();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private content(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              titleImage_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              day_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              month_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              year_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              author_ = s;
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              title_ = s;
              break;
            }
            case 66: {
              String s = input.readStringRequireUtf8();

              summary_ = s;
              break;
            }
            case 74: {
              String s = input.readStringRequireUtf8();

              mainTag_ = s;
              break;
            }
            case 80: {

              love_ = input.readInt32();
              break;
            }
            case 88: {

              commentNum_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HomeListOuterClass.internal_static_content_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HomeListOuterClass.internal_static_content_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              content.class, Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @Override
    public long getId() {
      return id_;
    }

    public static final int TITLEIMAGE_FIELD_NUMBER = 2;
    private volatile Object titleImage_;
    /**
     * <code>string titleImage = 2;</code>
     * @return The titleImage.
     */
    @Override
    public String getTitleImage() {
      Object ref = titleImage_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        titleImage_ = s;
        return s;
      }
    }
    /**
     * <code>string titleImage = 2;</code>
     * @return The bytes for titleImage.
     */
    @Override
    public com.google.protobuf.ByteString
        getTitleImageBytes() {
      Object ref = titleImage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        titleImage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DAY_FIELD_NUMBER = 3;
    private volatile Object day_;
    /**
     * <code>string day = 3;</code>
     * @return The day.
     */
    @Override
    public String getDay() {
      Object ref = day_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        day_ = s;
        return s;
      }
    }
    /**
     * <code>string day = 3;</code>
     * @return The bytes for day.
     */
    @Override
    public com.google.protobuf.ByteString
        getDayBytes() {
      Object ref = day_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        day_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MONTH_FIELD_NUMBER = 4;
    private volatile Object month_;
    /**
     * <code>string month = 4;</code>
     * @return The month.
     */
    @Override
    public String getMonth() {
      Object ref = month_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        month_ = s;
        return s;
      }
    }
    /**
     * <code>string month = 4;</code>
     * @return The bytes for month.
     */
    @Override
    public com.google.protobuf.ByteString
        getMonthBytes() {
      Object ref = month_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        month_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int YEAR_FIELD_NUMBER = 5;
    private volatile Object year_;
    /**
     * <code>string year = 5;</code>
     * @return The year.
     */
    @Override
    public String getYear() {
      Object ref = year_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        year_ = s;
        return s;
      }
    }
    /**
     * <code>string year = 5;</code>
     * @return The bytes for year.
     */
    @Override
    public com.google.protobuf.ByteString
        getYearBytes() {
      Object ref = year_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        year_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AUTHOR_FIELD_NUMBER = 6;
    private volatile Object author_;
    /**
     * <code>string author = 6;</code>
     * @return The author.
     */
    @Override
    public String getAuthor() {
      Object ref = author_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        author_ = s;
        return s;
      }
    }
    /**
     * <code>string author = 6;</code>
     * @return The bytes for author.
     */
    @Override
    public com.google.protobuf.ByteString
        getAuthorBytes() {
      Object ref = author_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        author_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TITLE_FIELD_NUMBER = 7;
    private volatile Object title_;
    /**
     * <code>string title = 7;</code>
     * @return The title.
     */
    @Override
    public String getTitle() {
      Object ref = title_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <code>string title = 7;</code>
     * @return The bytes for title.
     */
    @Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUMMARY_FIELD_NUMBER = 8;
    private volatile Object summary_;
    /**
     * <code>string summary = 8;</code>
     * @return The summary.
     */
    @Override
    public String getSummary() {
      Object ref = summary_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        summary_ = s;
        return s;
      }
    }
    /**
     * <code>string summary = 8;</code>
     * @return The bytes for summary.
     */
    @Override
    public com.google.protobuf.ByteString
        getSummaryBytes() {
      Object ref = summary_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        summary_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MAINTAG_FIELD_NUMBER = 9;
    private volatile Object mainTag_;
    /**
     * <code>string mainTag = 9;</code>
     * @return The mainTag.
     */
    @Override
    public String getMainTag() {
      Object ref = mainTag_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        mainTag_ = s;
        return s;
      }
    }
    /**
     * <code>string mainTag = 9;</code>
     * @return The bytes for mainTag.
     */
    @Override
    public com.google.protobuf.ByteString
        getMainTagBytes() {
      Object ref = mainTag_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        mainTag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOVE_FIELD_NUMBER = 10;
    private int love_;
    /**
     * <code>int32 love = 10;</code>
     * @return The love.
     */
    @Override
    public int getLove() {
      return love_;
    }

    public static final int COMMENTNUM_FIELD_NUMBER = 11;
    private int commentNum_;
    /**
     * <code>int32 commentNum = 11;</code>
     * @return The commentNum.
     */
    @Override
    public int getCommentNum() {
      return commentNum_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(titleImage_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, titleImage_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(day_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, day_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(month_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, month_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(year_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, year_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(author_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, author_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, title_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(summary_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, summary_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mainTag_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, mainTag_);
      }
      if (love_ != 0) {
        output.writeInt32(10, love_);
      }
      if (commentNum_ != 0) {
        output.writeInt32(11, commentNum_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(titleImage_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, titleImage_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(day_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, day_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(month_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, month_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(year_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, year_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(author_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, author_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, title_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(summary_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, summary_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mainTag_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, mainTag_);
      }
      if (love_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, love_);
      }
      if (commentNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, commentNum_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof content)) {
        return super.equals(obj);
      }
      content other = (content) obj;

      if (getId()
          != other.getId()) return false;
      if (!getTitleImage()
          .equals(other.getTitleImage())) return false;
      if (!getDay()
          .equals(other.getDay())) return false;
      if (!getMonth()
          .equals(other.getMonth())) return false;
      if (!getYear()
          .equals(other.getYear())) return false;
      if (!getAuthor()
          .equals(other.getAuthor())) return false;
      if (!getTitle()
          .equals(other.getTitle())) return false;
      if (!getSummary()
          .equals(other.getSummary())) return false;
      if (!getMainTag()
          .equals(other.getMainTag())) return false;
      if (getLove()
          != other.getLove()) return false;
      if (getCommentNum()
          != other.getCommentNum()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + TITLEIMAGE_FIELD_NUMBER;
      hash = (53 * hash) + getTitleImage().hashCode();
      hash = (37 * hash) + DAY_FIELD_NUMBER;
      hash = (53 * hash) + getDay().hashCode();
      hash = (37 * hash) + MONTH_FIELD_NUMBER;
      hash = (53 * hash) + getMonth().hashCode();
      hash = (37 * hash) + YEAR_FIELD_NUMBER;
      hash = (53 * hash) + getYear().hashCode();
      hash = (37 * hash) + AUTHOR_FIELD_NUMBER;
      hash = (53 * hash) + getAuthor().hashCode();
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (37 * hash) + SUMMARY_FIELD_NUMBER;
      hash = (53 * hash) + getSummary().hashCode();
      hash = (37 * hash) + MAINTAG_FIELD_NUMBER;
      hash = (53 * hash) + getMainTag().hashCode();
      hash = (37 * hash) + LOVE_FIELD_NUMBER;
      hash = (53 * hash) + getLove();
      hash = (37 * hash) + COMMENTNUM_FIELD_NUMBER;
      hash = (53 * hash) + getCommentNum();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static content parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static content parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static content parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static content parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static content parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static content parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static content parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static content parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static content parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static content parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static content parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static content parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(content prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code content}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:content)
        contentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HomeListOuterClass.internal_static_content_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HomeListOuterClass.internal_static_content_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                content.class, Builder.class);
      }

      // Construct using HomeListOuterClass.content.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        titleImage_ = "";

        day_ = "";

        month_ = "";

        year_ = "";

        author_ = "";

        title_ = "";

        summary_ = "";

        mainTag_ = "";

        love_ = 0;

        commentNum_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HomeListOuterClass.internal_static_content_descriptor;
      }

      @Override
      public content getDefaultInstanceForType() {
        return content.getDefaultInstance();
      }

      @Override
      public content build() {
        content result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public content buildPartial() {
        content result = new content(this);
        result.id_ = id_;
        result.titleImage_ = titleImage_;
        result.day_ = day_;
        result.month_ = month_;
        result.year_ = year_;
        result.author_ = author_;
        result.title_ = title_;
        result.summary_ = summary_;
        result.mainTag_ = mainTag_;
        result.love_ = love_;
        result.commentNum_ = commentNum_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof content) {
          return mergeFrom((content)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(content other) {
        if (other == content.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getTitleImage().isEmpty()) {
          titleImage_ = other.titleImage_;
          onChanged();
        }
        if (!other.getDay().isEmpty()) {
          day_ = other.day_;
          onChanged();
        }
        if (!other.getMonth().isEmpty()) {
          month_ = other.month_;
          onChanged();
        }
        if (!other.getYear().isEmpty()) {
          year_ = other.year_;
          onChanged();
        }
        if (!other.getAuthor().isEmpty()) {
          author_ = other.author_;
          onChanged();
        }
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          onChanged();
        }
        if (!other.getSummary().isEmpty()) {
          summary_ = other.summary_;
          onChanged();
        }
        if (!other.getMainTag().isEmpty()) {
          mainTag_ = other.mainTag_;
          onChanged();
        }
        if (other.getLove() != 0) {
          setLove(other.getLove());
        }
        if (other.getCommentNum() != 0) {
          setCommentNum(other.getCommentNum());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        content parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (content) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @Override
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private Object titleImage_ = "";
      /**
       * <code>string titleImage = 2;</code>
       * @return The titleImage.
       */
      public String getTitleImage() {
        Object ref = titleImage_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          titleImage_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string titleImage = 2;</code>
       * @return The bytes for titleImage.
       */
      public com.google.protobuf.ByteString
          getTitleImageBytes() {
        Object ref = titleImage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          titleImage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string titleImage = 2;</code>
       * @param value The titleImage to set.
       * @return This builder for chaining.
       */
      public Builder setTitleImage(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        titleImage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string titleImage = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTitleImage() {
        
        titleImage_ = getDefaultInstance().getTitleImage();
        onChanged();
        return this;
      }
      /**
       * <code>string titleImage = 2;</code>
       * @param value The bytes for titleImage to set.
       * @return This builder for chaining.
       */
      public Builder setTitleImageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        titleImage_ = value;
        onChanged();
        return this;
      }

      private Object day_ = "";
      /**
       * <code>string day = 3;</code>
       * @return The day.
       */
      public String getDay() {
        Object ref = day_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          day_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string day = 3;</code>
       * @return The bytes for day.
       */
      public com.google.protobuf.ByteString
          getDayBytes() {
        Object ref = day_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          day_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string day = 3;</code>
       * @param value The day to set.
       * @return This builder for chaining.
       */
      public Builder setDay(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        day_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string day = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDay() {
        
        day_ = getDefaultInstance().getDay();
        onChanged();
        return this;
      }
      /**
       * <code>string day = 3;</code>
       * @param value The bytes for day to set.
       * @return This builder for chaining.
       */
      public Builder setDayBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        day_ = value;
        onChanged();
        return this;
      }

      private Object month_ = "";
      /**
       * <code>string month = 4;</code>
       * @return The month.
       */
      public String getMonth() {
        Object ref = month_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          month_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string month = 4;</code>
       * @return The bytes for month.
       */
      public com.google.protobuf.ByteString
          getMonthBytes() {
        Object ref = month_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          month_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string month = 4;</code>
       * @param value The month to set.
       * @return This builder for chaining.
       */
      public Builder setMonth(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        month_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string month = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMonth() {
        
        month_ = getDefaultInstance().getMonth();
        onChanged();
        return this;
      }
      /**
       * <code>string month = 4;</code>
       * @param value The bytes for month to set.
       * @return This builder for chaining.
       */
      public Builder setMonthBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        month_ = value;
        onChanged();
        return this;
      }

      private Object year_ = "";
      /**
       * <code>string year = 5;</code>
       * @return The year.
       */
      public String getYear() {
        Object ref = year_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          year_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string year = 5;</code>
       * @return The bytes for year.
       */
      public com.google.protobuf.ByteString
          getYearBytes() {
        Object ref = year_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          year_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string year = 5;</code>
       * @param value The year to set.
       * @return This builder for chaining.
       */
      public Builder setYear(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        year_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string year = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearYear() {
        
        year_ = getDefaultInstance().getYear();
        onChanged();
        return this;
      }
      /**
       * <code>string year = 5;</code>
       * @param value The bytes for year to set.
       * @return This builder for chaining.
       */
      public Builder setYearBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        year_ = value;
        onChanged();
        return this;
      }

      private Object author_ = "";
      /**
       * <code>string author = 6;</code>
       * @return The author.
       */
      public String getAuthor() {
        Object ref = author_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          author_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string author = 6;</code>
       * @return The bytes for author.
       */
      public com.google.protobuf.ByteString
          getAuthorBytes() {
        Object ref = author_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          author_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string author = 6;</code>
       * @param value The author to set.
       * @return This builder for chaining.
       */
      public Builder setAuthor(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        author_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string author = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearAuthor() {
        
        author_ = getDefaultInstance().getAuthor();
        onChanged();
        return this;
      }
      /**
       * <code>string author = 6;</code>
       * @param value The bytes for author to set.
       * @return This builder for chaining.
       */
      public Builder setAuthorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        author_ = value;
        onChanged();
        return this;
      }

      private Object title_ = "";
      /**
       * <code>string title = 7;</code>
       * @return The title.
       */
      public String getTitle() {
        Object ref = title_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string title = 7;</code>
       * @return The bytes for title.
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string title = 7;</code>
       * @param value The title to set.
       * @return This builder for chaining.
       */
      public Builder setTitle(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string title = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearTitle() {
        
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>string title = 7;</code>
       * @param value The bytes for title to set.
       * @return This builder for chaining.
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        title_ = value;
        onChanged();
        return this;
      }

      private Object summary_ = "";
      /**
       * <code>string summary = 8;</code>
       * @return The summary.
       */
      public String getSummary() {
        Object ref = summary_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          summary_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string summary = 8;</code>
       * @return The bytes for summary.
       */
      public com.google.protobuf.ByteString
          getSummaryBytes() {
        Object ref = summary_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          summary_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string summary = 8;</code>
       * @param value The summary to set.
       * @return This builder for chaining.
       */
      public Builder setSummary(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        summary_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string summary = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearSummary() {
        
        summary_ = getDefaultInstance().getSummary();
        onChanged();
        return this;
      }
      /**
       * <code>string summary = 8;</code>
       * @param value The bytes for summary to set.
       * @return This builder for chaining.
       */
      public Builder setSummaryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        summary_ = value;
        onChanged();
        return this;
      }

      private Object mainTag_ = "";
      /**
       * <code>string mainTag = 9;</code>
       * @return The mainTag.
       */
      public String getMainTag() {
        Object ref = mainTag_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          mainTag_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string mainTag = 9;</code>
       * @return The bytes for mainTag.
       */
      public com.google.protobuf.ByteString
          getMainTagBytes() {
        Object ref = mainTag_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          mainTag_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string mainTag = 9;</code>
       * @param value The mainTag to set.
       * @return This builder for chaining.
       */
      public Builder setMainTag(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mainTag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string mainTag = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearMainTag() {
        
        mainTag_ = getDefaultInstance().getMainTag();
        onChanged();
        return this;
      }
      /**
       * <code>string mainTag = 9;</code>
       * @param value The bytes for mainTag to set.
       * @return This builder for chaining.
       */
      public Builder setMainTagBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mainTag_ = value;
        onChanged();
        return this;
      }

      private int love_ ;
      /**
       * <code>int32 love = 10;</code>
       * @return The love.
       */
      @Override
      public int getLove() {
        return love_;
      }
      /**
       * <code>int32 love = 10;</code>
       * @param value The love to set.
       * @return This builder for chaining.
       */
      public Builder setLove(int value) {
        
        love_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 love = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearLove() {
        
        love_ = 0;
        onChanged();
        return this;
      }

      private int commentNum_ ;
      /**
       * <code>int32 commentNum = 11;</code>
       * @return The commentNum.
       */
      @Override
      public int getCommentNum() {
        return commentNum_;
      }
      /**
       * <code>int32 commentNum = 11;</code>
       * @param value The commentNum to set.
       * @return This builder for chaining.
       */
      public Builder setCommentNum(int value) {
        
        commentNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 commentNum = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearCommentNum() {
        
        commentNum_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:content)
    }

    // @@protoc_insertion_point(class_scope:content)
    private static final content DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new content();
    }

    public static content getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<content>
        PARSER = new com.google.protobuf.AbstractParser<content>() {
      @Override
      public content parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new content(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<content> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<content> getParserForType() {
      return PARSER;
    }

    @Override
    public content getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HomeList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HomeList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_content_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_content_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016HomeList.proto\"D\n\010HomeList\022\027\n\005array\030\001 " +
      "\003(\0132\010.content\022\014\n\004page\030\002 \001(\005\022\021\n\ttotalPage" +
      "\030\003 \001(\005\"\266\001\n\007content\022\n\n\002id\030\001 \001(\003\022\022\n\ntitleI" +
      "mage\030\002 \001(\t\022\013\n\003day\030\003 \001(\t\022\r\n\005month\030\004 \001(\t\022\014" +
      "\n\004year\030\005 \001(\t\022\016\n\006author\030\006 \001(\t\022\r\n\005title\030\007 " +
      "\001(\t\022\017\n\007summary\030\010 \001(\t\022\017\n\007mainTag\030\t \001(\t\022\014\n" +
      "\004love\030\n \001(\005\022\022\n\ncommentNum\030\013 \001(\005b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_HomeList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HomeList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HomeList_descriptor,
        new String[] { "Array", "Page", "TotalPage", });
    internal_static_content_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_content_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_content_descriptor,
        new String[] { "Id", "TitleImage", "Day", "Month", "Year", "Author", "Title", "Summary", "MainTag", "Love", "CommentNum", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
