package com.zzj.vo;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PicTimeline.proto

public final class PicTimeline {
  private PicTimeline() {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public interface PicsOrBuilder extends
          // @@protoc_insertion_point(interface_extends:Pics)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .PicsList array = 1;</code>
     */
    java.util.List<PicTimeline.PicsList>
    getArrayList();

    /**
     * <code>repeated .PicsList array = 1;</code>
     */
    PicTimeline.PicsList getArray(int index);

    /**
     * <code>repeated .PicsList array = 1;</code>
     */
    int getArrayCount();

    /**
     * <code>repeated .PicsList array = 1;</code>
     */
    java.util.List<? extends PicTimeline.PicsListOrBuilder>
    getArrayOrBuilderList();

    /**
     * <code>repeated .PicsList array = 1;</code>
     */
    PicTimeline.PicsListOrBuilder getArrayOrBuilder(
            int index);

    /**
     * <code>int32 hasNext = 2;</code>
     *
     * @return The hasNext.
     */
    int getHasNext();
  }

  /**
   * Protobuf type {@code Pics}
   */
  public static final class Pics extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:Pics)
          PicsOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use Pics.newBuilder() to construct.
    private Pics(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private Pics() {
      array_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
      return new Pics();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }

    private Pics(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                array_ = new java.util.ArrayList<PicTimeline.PicsList>();
                mutable_bitField0_ |= 0x00000001;
              }
              array_.add(
                      input.readMessage(PicTimeline.PicsList.parser(), extensionRegistry));
              break;
            }
            case 16: {

              hasNext_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                      input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          array_ = java.util.Collections.unmodifiableList(array_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return PicTimeline.internal_static_Pics_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return PicTimeline.internal_static_Pics_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      PicTimeline.Pics.class, PicTimeline.Pics.Builder.class);
    }

    public static final int ARRAY_FIELD_NUMBER = 1;
    private java.util.List<PicTimeline.PicsList> array_;

    /**
     * <code>repeated .PicsList array = 1;</code>
     */
    @java.lang.Override
    public java.util.List<PicTimeline.PicsList> getArrayList() {
      return array_;
    }

    /**
     * <code>repeated .PicsList array = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends PicTimeline.PicsListOrBuilder>
    getArrayOrBuilderList() {
      return array_;
    }

    /**
     * <code>repeated .PicsList array = 1;</code>
     */
    @java.lang.Override
    public int getArrayCount() {
      return array_.size();
    }

    /**
     * <code>repeated .PicsList array = 1;</code>
     */
    @java.lang.Override
    public PicTimeline.PicsList getArray(int index) {
      return array_.get(index);
    }

    /**
     * <code>repeated .PicsList array = 1;</code>
     */
    @java.lang.Override
    public PicTimeline.PicsListOrBuilder getArrayOrBuilder(
            int index) {
      return array_.get(index);
    }

    public static final int HASNEXT_FIELD_NUMBER = 2;
    private int hasNext_;

    /**
     * <code>int32 hasNext = 2;</code>
     *
     * @return The hasNext.
     */
    @java.lang.Override
    public int getHasNext() {
      return hasNext_;
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      for (int i = 0; i < array_.size(); i++) {
        output.writeMessage(1, array_.get(i));
      }
      if (hasNext_ != 0) {
        output.writeInt32(2, hasNext_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < array_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
                .computeMessageSize(1, array_.get(i));
      }
      if (hasNext_ != 0) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(2, hasNext_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof PicTimeline.Pics)) {
        return super.equals(obj);
      }
      PicTimeline.Pics other = (PicTimeline.Pics) obj;

      if (!getArrayList()
              .equals(other.getArrayList())) return false;
      if (getHasNext()
              != other.getHasNext()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getArrayCount() > 0) {
        hash = (37 * hash) + ARRAY_FIELD_NUMBER;
        hash = (53 * hash) + getArrayList().hashCode();
      }
      hash = (37 * hash) + HASNEXT_FIELD_NUMBER;
      hash = (53 * hash) + getHasNext();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PicTimeline.Pics parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static PicTimeline.Pics parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static PicTimeline.Pics parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static PicTimeline.Pics parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static PicTimeline.Pics parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static PicTimeline.Pics parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static PicTimeline.Pics parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }

    public static PicTimeline.Pics parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static PicTimeline.Pics parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }

    public static PicTimeline.Pics parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static PicTimeline.Pics parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }

    public static PicTimeline.Pics parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(PicTimeline.Pics prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * Protobuf type {@code Pics}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:Pics)
            PicTimeline.PicsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return PicTimeline.internal_static_Pics_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return PicTimeline.internal_static_Pics_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        PicTimeline.Pics.class, PicTimeline.Pics.Builder.class);
      }

      // Construct using PicTimeline.Pics.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getArrayFieldBuilder();
        }
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (arrayBuilder_ == null) {
          array_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          arrayBuilder_.clear();
        }
        hasNext_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return PicTimeline.internal_static_Pics_descriptor;
      }

      @java.lang.Override
      public PicTimeline.Pics getDefaultInstanceForType() {
        return PicTimeline.Pics.getDefaultInstance();
      }

      @java.lang.Override
      public PicTimeline.Pics build() {
        PicTimeline.Pics result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public PicTimeline.Pics buildPartial() {
        PicTimeline.Pics result = new PicTimeline.Pics(this);
        int from_bitField0_ = bitField0_;
        if (arrayBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            array_ = java.util.Collections.unmodifiableList(array_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.array_ = array_;
        } else {
          result.array_ = arrayBuilder_.build();
        }
        result.hasNext_ = hasNext_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }

      @java.lang.Override
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PicTimeline.Pics) {
          return mergeFrom((PicTimeline.Pics) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PicTimeline.Pics other) {
        if (other == PicTimeline.Pics.getDefaultInstance()) return this;
        if (arrayBuilder_ == null) {
          if (!other.array_.isEmpty()) {
            if (array_.isEmpty()) {
              array_ = other.array_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureArrayIsMutable();
              array_.addAll(other.array_);
            }
            onChanged();
          }
        } else {
          if (!other.array_.isEmpty()) {
            if (arrayBuilder_.isEmpty()) {
              arrayBuilder_.dispose();
              arrayBuilder_ = null;
              array_ = other.array_;
              bitField0_ = (bitField0_ & ~0x00000001);
              arrayBuilder_ =
                      com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                              getArrayFieldBuilder() : null;
            } else {
              arrayBuilder_.addAllMessages(other.array_);
            }
          }
        }
        if (other.getHasNext() != 0) {
          setHasNext(other.getHasNext());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        PicTimeline.Pics parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PicTimeline.Pics) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int bitField0_;

      private java.util.List<PicTimeline.PicsList> array_ =
              java.util.Collections.emptyList();

      private void ensureArrayIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          array_ = new java.util.ArrayList<PicTimeline.PicsList>(array_);
          bitField0_ |= 0x00000001;
        }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
              PicTimeline.PicsList, PicTimeline.PicsList.Builder, PicTimeline.PicsListOrBuilder> arrayBuilder_;

      /**
       * <code>repeated .PicsList array = 1;</code>
       */
      public java.util.List<PicTimeline.PicsList> getArrayList() {
        if (arrayBuilder_ == null) {
          return java.util.Collections.unmodifiableList(array_);
        } else {
          return arrayBuilder_.getMessageList();
        }
      }

      /**
       * <code>repeated .PicsList array = 1;</code>
       */
      public int getArrayCount() {
        if (arrayBuilder_ == null) {
          return array_.size();
        } else {
          return arrayBuilder_.getCount();
        }
      }

      /**
       * <code>repeated .PicsList array = 1;</code>
       */
      public PicTimeline.PicsList getArray(int index) {
        if (arrayBuilder_ == null) {
          return array_.get(index);
        } else {
          return arrayBuilder_.getMessage(index);
        }
      }

      /**
       * <code>repeated .PicsList array = 1;</code>
       */
      public Builder setArray(
              int index, PicTimeline.PicsList value) {
        if (arrayBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArrayIsMutable();
          array_.set(index, value);
          onChanged();
        } else {
          arrayBuilder_.setMessage(index, value);
        }
        return this;
      }

      /**
       * <code>repeated .PicsList array = 1;</code>
       */
      public Builder setArray(
              int index, PicTimeline.PicsList.Builder builderForValue) {
        if (arrayBuilder_ == null) {
          ensureArrayIsMutable();
          array_.set(index, builderForValue.build());
          onChanged();
        } else {
          arrayBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }

      /**
       * <code>repeated .PicsList array = 1;</code>
       */
      public Builder addArray(PicTimeline.PicsList value) {
        if (arrayBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArrayIsMutable();
          array_.add(value);
          onChanged();
        } else {
          arrayBuilder_.addMessage(value);
        }
        return this;
      }

      /**
       * <code>repeated .PicsList array = 1;</code>
       */
      public Builder addArray(
              int index, PicTimeline.PicsList value) {
        if (arrayBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArrayIsMutable();
          array_.add(index, value);
          onChanged();
        } else {
          arrayBuilder_.addMessage(index, value);
        }
        return this;
      }

      /**
       * <code>repeated .PicsList array = 1;</code>
       */
      public Builder addArray(
              PicTimeline.PicsList.Builder builderForValue) {
        if (arrayBuilder_ == null) {
          ensureArrayIsMutable();
          array_.add(builderForValue.build());
          onChanged();
        } else {
          arrayBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }

      /**
       * <code>repeated .PicsList array = 1;</code>
       */
      public Builder addArray(
              int index, PicTimeline.PicsList.Builder builderForValue) {
        if (arrayBuilder_ == null) {
          ensureArrayIsMutable();
          array_.add(index, builderForValue.build());
          onChanged();
        } else {
          arrayBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }

      /**
       * <code>repeated .PicsList array = 1;</code>
       */
      public Builder addAllArray(
              java.lang.Iterable<? extends PicTimeline.PicsList> values) {
        if (arrayBuilder_ == null) {
          ensureArrayIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
                  values, array_);
          onChanged();
        } else {
          arrayBuilder_.addAllMessages(values);
        }
        return this;
      }

      /**
       * <code>repeated .PicsList array = 1;</code>
       */
      public Builder clearArray() {
        if (arrayBuilder_ == null) {
          array_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          arrayBuilder_.clear();
        }
        return this;
      }

      /**
       * <code>repeated .PicsList array = 1;</code>
       */
      public Builder removeArray(int index) {
        if (arrayBuilder_ == null) {
          ensureArrayIsMutable();
          array_.remove(index);
          onChanged();
        } else {
          arrayBuilder_.remove(index);
        }
        return this;
      }

      /**
       * <code>repeated .PicsList array = 1;</code>
       */
      public PicTimeline.PicsList.Builder getArrayBuilder(
              int index) {
        return getArrayFieldBuilder().getBuilder(index);
      }

      /**
       * <code>repeated .PicsList array = 1;</code>
       */
      public PicTimeline.PicsListOrBuilder getArrayOrBuilder(
              int index) {
        if (arrayBuilder_ == null) {
          return array_.get(index);
        } else {
          return arrayBuilder_.getMessageOrBuilder(index);
        }
      }

      /**
       * <code>repeated .PicsList array = 1;</code>
       */
      public java.util.List<? extends PicTimeline.PicsListOrBuilder>
      getArrayOrBuilderList() {
        if (arrayBuilder_ != null) {
          return arrayBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(array_);
        }
      }

      /**
       * <code>repeated .PicsList array = 1;</code>
       */
      public PicTimeline.PicsList.Builder addArrayBuilder() {
        return getArrayFieldBuilder().addBuilder(
                PicTimeline.PicsList.getDefaultInstance());
      }

      /**
       * <code>repeated .PicsList array = 1;</code>
       */
      public PicTimeline.PicsList.Builder addArrayBuilder(
              int index) {
        return getArrayFieldBuilder().addBuilder(
                index, PicTimeline.PicsList.getDefaultInstance());
      }

      /**
       * <code>repeated .PicsList array = 1;</code>
       */
      public java.util.List<PicTimeline.PicsList.Builder>
      getArrayBuilderList() {
        return getArrayFieldBuilder().getBuilderList();
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
              PicTimeline.PicsList, PicTimeline.PicsList.Builder, PicTimeline.PicsListOrBuilder>
      getArrayFieldBuilder() {
        if (arrayBuilder_ == null) {
          arrayBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                  PicTimeline.PicsList, PicTimeline.PicsList.Builder, PicTimeline.PicsListOrBuilder>(
                  array_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          array_ = null;
        }
        return arrayBuilder_;
      }

      private int hasNext_;

      /**
       * <code>int32 hasNext = 2;</code>
       *
       * @return The hasNext.
       */
      @java.lang.Override
      public int getHasNext() {
        return hasNext_;
      }

      /**
       * <code>int32 hasNext = 2;</code>
       *
       * @param value The hasNext to set.
       * @return This builder for chaining.
       */
      public Builder setHasNext(int value) {

        hasNext_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>int32 hasNext = 2;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearHasNext() {

        hasNext_ = 0;
        onChanged();
        return this;
      }

      @java.lang.Override
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Pics)
    }

    // @@protoc_insertion_point(class_scope:Pics)
    private static final PicTimeline.Pics DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE = new PicTimeline.Pics();
    }

    public static PicTimeline.Pics getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Pics>
            PARSER = new com.google.protobuf.AbstractParser<Pics>() {
      @java.lang.Override
      public Pics parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return new Pics(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Pics> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Pics> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public PicTimeline.Pics getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PicsListOrBuilder extends
          // @@protoc_insertion_point(interface_extends:PicsList)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string dateTitle = 1;</code>
     *
     * @return The dateTitle.
     */
    java.lang.String getDateTitle();

    /**
     * <code>string dateTitle = 1;</code>
     *
     * @return The bytes for dateTitle.
     */
    com.google.protobuf.ByteString
    getDateTitleBytes();

    /**
     * <code>repeated .Pic data = 2;</code>
     */
    java.util.List<PicTimeline.Pic>
    getDataList();

    /**
     * <code>repeated .Pic data = 2;</code>
     */
    PicTimeline.Pic getData(int index);

    /**
     * <code>repeated .Pic data = 2;</code>
     */
    int getDataCount();

    /**
     * <code>repeated .Pic data = 2;</code>
     */
    java.util.List<? extends PicTimeline.PicOrBuilder>
    getDataOrBuilderList();

    /**
     * <code>repeated .Pic data = 2;</code>
     */
    PicTimeline.PicOrBuilder getDataOrBuilder(
            int index);
  }

  /**
   * Protobuf type {@code PicsList}
   */
  public static final class PicsList extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:PicsList)
          PicsListOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use PicsList.newBuilder() to construct.
    private PicsList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private PicsList() {
      dateTitle_ = "";
      data_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
      return new PicsList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }

    private PicsList(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              dateTitle_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                data_ = new java.util.ArrayList<PicTimeline.Pic>();
                mutable_bitField0_ |= 0x00000001;
              }
              data_.add(
                      input.readMessage(PicTimeline.Pic.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                      input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          data_ = java.util.Collections.unmodifiableList(data_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return PicTimeline.internal_static_PicsList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return PicTimeline.internal_static_PicsList_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      PicTimeline.PicsList.class, PicTimeline.PicsList.Builder.class);
    }

    public static final int DATETITLE_FIELD_NUMBER = 1;
    private volatile java.lang.Object dateTitle_;

    /**
     * <code>string dateTitle = 1;</code>
     *
     * @return The dateTitle.
     */
    @java.lang.Override
    public java.lang.String getDateTitle() {
      java.lang.Object ref = dateTitle_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dateTitle_ = s;
        return s;
      }
    }

    /**
     * <code>string dateTitle = 1;</code>
     *
     * @return The bytes for dateTitle.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getDateTitleBytes() {
      java.lang.Object ref = dateTitle_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        dateTitle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private java.util.List<PicTimeline.Pic> data_;

    /**
     * <code>repeated .Pic data = 2;</code>
     */
    @java.lang.Override
    public java.util.List<PicTimeline.Pic> getDataList() {
      return data_;
    }

    /**
     * <code>repeated .Pic data = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends PicTimeline.PicOrBuilder>
    getDataOrBuilderList() {
      return data_;
    }

    /**
     * <code>repeated .Pic data = 2;</code>
     */
    @java.lang.Override
    public int getDataCount() {
      return data_.size();
    }

    /**
     * <code>repeated .Pic data = 2;</code>
     */
    @java.lang.Override
    public PicTimeline.Pic getData(int index) {
      return data_.get(index);
    }

    /**
     * <code>repeated .Pic data = 2;</code>
     */
    @java.lang.Override
    public PicTimeline.PicOrBuilder getDataOrBuilder(
            int index) {
      return data_.get(index);
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dateTitle_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, dateTitle_);
      }
      for (int i = 0; i < data_.size(); i++) {
        output.writeMessage(2, data_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dateTitle_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, dateTitle_);
      }
      for (int i = 0; i < data_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
                .computeMessageSize(2, data_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof PicTimeline.PicsList)) {
        return super.equals(obj);
      }
      PicTimeline.PicsList other = (PicTimeline.PicsList) obj;

      if (!getDateTitle()
              .equals(other.getDateTitle())) return false;
      if (!getDataList()
              .equals(other.getDataList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATETITLE_FIELD_NUMBER;
      hash = (53 * hash) + getDateTitle().hashCode();
      if (getDataCount() > 0) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getDataList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PicTimeline.PicsList parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static PicTimeline.PicsList parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static PicTimeline.PicsList parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static PicTimeline.PicsList parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static PicTimeline.PicsList parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static PicTimeline.PicsList parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static PicTimeline.PicsList parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }

    public static PicTimeline.PicsList parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static PicTimeline.PicsList parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }

    public static PicTimeline.PicsList parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static PicTimeline.PicsList parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }

    public static PicTimeline.PicsList parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(PicTimeline.PicsList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * Protobuf type {@code PicsList}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:PicsList)
            PicTimeline.PicsListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return PicTimeline.internal_static_PicsList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return PicTimeline.internal_static_PicsList_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        PicTimeline.PicsList.class, PicTimeline.PicsList.Builder.class);
      }

      // Construct using PicTimeline.PicsList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDataFieldBuilder();
        }
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        dateTitle_ = "";

        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          dataBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return PicTimeline.internal_static_PicsList_descriptor;
      }

      @java.lang.Override
      public PicTimeline.PicsList getDefaultInstanceForType() {
        return PicTimeline.PicsList.getDefaultInstance();
      }

      @java.lang.Override
      public PicTimeline.PicsList build() {
        PicTimeline.PicsList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public PicTimeline.PicsList buildPartial() {
        PicTimeline.PicsList result = new PicTimeline.PicsList(this);
        int from_bitField0_ = bitField0_;
        result.dateTitle_ = dateTitle_;
        if (dataBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            data_ = java.util.Collections.unmodifiableList(data_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }

      @java.lang.Override
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PicTimeline.PicsList) {
          return mergeFrom((PicTimeline.PicsList) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PicTimeline.PicsList other) {
        if (other == PicTimeline.PicsList.getDefaultInstance()) return this;
        if (!other.getDateTitle().isEmpty()) {
          dateTitle_ = other.dateTitle_;
          onChanged();
        }
        if (dataBuilder_ == null) {
          if (!other.data_.isEmpty()) {
            if (data_.isEmpty()) {
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDataIsMutable();
              data_.addAll(other.data_);
            }
            onChanged();
          }
        } else {
          if (!other.data_.isEmpty()) {
            if (dataBuilder_.isEmpty()) {
              dataBuilder_.dispose();
              dataBuilder_ = null;
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000001);
              dataBuilder_ =
                      com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                              getDataFieldBuilder() : null;
            } else {
              dataBuilder_.addAllMessages(other.data_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        PicTimeline.PicsList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PicTimeline.PicsList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int bitField0_;

      private java.lang.Object dateTitle_ = "";

      /**
       * <code>string dateTitle = 1;</code>
       *
       * @return The dateTitle.
       */
      public java.lang.String getDateTitle() {
        java.lang.Object ref = dateTitle_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dateTitle_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>string dateTitle = 1;</code>
       *
       * @return The bytes for dateTitle.
       */
      public com.google.protobuf.ByteString
      getDateTitleBytes() {
        java.lang.Object ref = dateTitle_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          dateTitle_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string dateTitle = 1;</code>
       *
       * @param value The dateTitle to set.
       * @return This builder for chaining.
       */
      public Builder setDateTitle(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        dateTitle_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string dateTitle = 1;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearDateTitle() {

        dateTitle_ = getDefaultInstance().getDateTitle();
        onChanged();
        return this;
      }

      /**
       * <code>string dateTitle = 1;</code>
       *
       * @param value The bytes for dateTitle to set.
       * @return This builder for chaining.
       */
      public Builder setDateTitleBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        dateTitle_ = value;
        onChanged();
        return this;
      }

      private java.util.List<PicTimeline.Pic> data_ =
              java.util.Collections.emptyList();

      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          data_ = new java.util.ArrayList<PicTimeline.Pic>(data_);
          bitField0_ |= 0x00000001;
        }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
              PicTimeline.Pic, PicTimeline.Pic.Builder, PicTimeline.PicOrBuilder> dataBuilder_;

      /**
       * <code>repeated .Pic data = 2;</code>
       */
      public java.util.List<PicTimeline.Pic> getDataList() {
        if (dataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(data_);
        } else {
          return dataBuilder_.getMessageList();
        }
      }

      /**
       * <code>repeated .Pic data = 2;</code>
       */
      public int getDataCount() {
        if (dataBuilder_ == null) {
          return data_.size();
        } else {
          return dataBuilder_.getCount();
        }
      }

      /**
       * <code>repeated .Pic data = 2;</code>
       */
      public PicTimeline.Pic getData(int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);
        } else {
          return dataBuilder_.getMessage(index);
        }
      }

      /**
       * <code>repeated .Pic data = 2;</code>
       */
      public Builder setData(
              int index, PicTimeline.Pic value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.set(index, value);
          onChanged();
        } else {
          dataBuilder_.setMessage(index, value);
        }
        return this;
      }

      /**
       * <code>repeated .Pic data = 2;</code>
       */
      public Builder setData(
              int index, PicTimeline.Pic.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.set(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }

      /**
       * <code>repeated .Pic data = 2;</code>
       */
      public Builder addData(PicTimeline.Pic value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(value);
          onChanged();
        } else {
          dataBuilder_.addMessage(value);
        }
        return this;
      }

      /**
       * <code>repeated .Pic data = 2;</code>
       */
      public Builder addData(
              int index, PicTimeline.Pic value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(index, value);
          onChanged();
        } else {
          dataBuilder_.addMessage(index, value);
        }
        return this;
      }

      /**
       * <code>repeated .Pic data = 2;</code>
       */
      public Builder addData(
              PicTimeline.Pic.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }

      /**
       * <code>repeated .Pic data = 2;</code>
       */
      public Builder addData(
              int index, PicTimeline.Pic.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }

      /**
       * <code>repeated .Pic data = 2;</code>
       */
      public Builder addAllData(
              java.lang.Iterable<? extends PicTimeline.Pic> values) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
                  values, data_);
          onChanged();
        } else {
          dataBuilder_.addAllMessages(values);
        }
        return this;
      }

      /**
       * <code>repeated .Pic data = 2;</code>
       */
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          dataBuilder_.clear();
        }
        return this;
      }

      /**
       * <code>repeated .Pic data = 2;</code>
       */
      public Builder removeData(int index) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.remove(index);
          onChanged();
        } else {
          dataBuilder_.remove(index);
        }
        return this;
      }

      /**
       * <code>repeated .Pic data = 2;</code>
       */
      public PicTimeline.Pic.Builder getDataBuilder(
              int index) {
        return getDataFieldBuilder().getBuilder(index);
      }

      /**
       * <code>repeated .Pic data = 2;</code>
       */
      public PicTimeline.PicOrBuilder getDataOrBuilder(
              int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);
        } else {
          return dataBuilder_.getMessageOrBuilder(index);
        }
      }

      /**
       * <code>repeated .Pic data = 2;</code>
       */
      public java.util.List<? extends PicTimeline.PicOrBuilder>
      getDataOrBuilderList() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(data_);
        }
      }

      /**
       * <code>repeated .Pic data = 2;</code>
       */
      public PicTimeline.Pic.Builder addDataBuilder() {
        return getDataFieldBuilder().addBuilder(
                PicTimeline.Pic.getDefaultInstance());
      }

      /**
       * <code>repeated .Pic data = 2;</code>
       */
      public PicTimeline.Pic.Builder addDataBuilder(
              int index) {
        return getDataFieldBuilder().addBuilder(
                index, PicTimeline.Pic.getDefaultInstance());
      }

      /**
       * <code>repeated .Pic data = 2;</code>
       */
      public java.util.List<PicTimeline.Pic.Builder>
      getDataBuilderList() {
        return getDataFieldBuilder().getBuilderList();
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
              PicTimeline.Pic, PicTimeline.Pic.Builder, PicTimeline.PicOrBuilder>
      getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                  PicTimeline.Pic, PicTimeline.Pic.Builder, PicTimeline.PicOrBuilder>(
                  data_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }

      @java.lang.Override
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PicsList)
    }

    // @@protoc_insertion_point(class_scope:PicsList)
    private static final PicTimeline.PicsList DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE = new PicTimeline.PicsList();
    }

    public static PicTimeline.PicsList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PicsList>
            PARSER = new com.google.protobuf.AbstractParser<PicsList>() {
      @java.lang.Override
      public PicsList parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return new PicsList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PicsList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PicsList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public PicTimeline.PicsList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PicOrBuilder extends
          // @@protoc_insertion_point(interface_extends:Pic)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string src = 1;</code>
     *
     * @return The src.
     */
    java.lang.String getSrc();

    /**
     * <code>string src = 1;</code>
     *
     * @return The bytes for src.
     */
    com.google.protobuf.ByteString
    getSrcBytes();

    /**
     * <code>string day = 2;</code>
     *
     * @return The day.
     */
    java.lang.String getDay();

    /**
     * <code>string day = 2;</code>
     *
     * @return The bytes for day.
     */
    com.google.protobuf.ByteString
    getDayBytes();

    /**
     * <code>string month = 3;</code>
     *
     * @return The month.
     */
    java.lang.String getMonth();

    /**
     * <code>string month = 3;</code>
     *
     * @return The bytes for month.
     */
    com.google.protobuf.ByteString
    getMonthBytes();

    /**
     * <code>string year = 4;</code>
     *
     * @return The year.
     */
    java.lang.String getYear();

    /**
     * <code>string year = 4;</code>
     *
     * @return The bytes for year.
     */
    com.google.protobuf.ByteString
    getYearBytes();
  }

  /**
   * Protobuf type {@code Pic}
   */
  public static final class Pic extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:Pic)
          PicOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use Pic.newBuilder() to construct.
    private Pic(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private Pic() {
      src_ = "";
      day_ = "";
      month_ = "";
      year_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
      return new Pic();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }

    private Pic(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              src_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              day_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              month_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              year_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                      input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return PicTimeline.internal_static_Pic_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return PicTimeline.internal_static_Pic_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      PicTimeline.Pic.class, PicTimeline.Pic.Builder.class);
    }

    public static final int SRC_FIELD_NUMBER = 1;
    private volatile java.lang.Object src_;

    /**
     * <code>string src = 1;</code>
     *
     * @return The src.
     */
    @java.lang.Override
    public java.lang.String getSrc() {
      java.lang.Object ref = src_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        src_ = s;
        return s;
      }
    }

    /**
     * <code>string src = 1;</code>
     *
     * @return The bytes for src.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getSrcBytes() {
      java.lang.Object ref = src_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        src_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DAY_FIELD_NUMBER = 2;
    private volatile java.lang.Object day_;

    /**
     * <code>string day = 2;</code>
     *
     * @return The day.
     */
    @java.lang.Override
    public java.lang.String getDay() {
      java.lang.Object ref = day_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        day_ = s;
        return s;
      }
    }

    /**
     * <code>string day = 2;</code>
     *
     * @return The bytes for day.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getDayBytes() {
      java.lang.Object ref = day_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        day_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MONTH_FIELD_NUMBER = 3;
    private volatile java.lang.Object month_;

    /**
     * <code>string month = 3;</code>
     *
     * @return The month.
     */
    @java.lang.Override
    public java.lang.String getMonth() {
      java.lang.Object ref = month_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        month_ = s;
        return s;
      }
    }

    /**
     * <code>string month = 3;</code>
     *
     * @return The bytes for month.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getMonthBytes() {
      java.lang.Object ref = month_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        month_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int YEAR_FIELD_NUMBER = 4;
    private volatile java.lang.Object year_;

    /**
     * <code>string year = 4;</code>
     *
     * @return The year.
     */
    @java.lang.Override
    public java.lang.String getYear() {
      java.lang.Object ref = year_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        year_ = s;
        return s;
      }
    }

    /**
     * <code>string year = 4;</code>
     *
     * @return The bytes for year.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getYearBytes() {
      java.lang.Object ref = year_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        year_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(src_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, src_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(day_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, day_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(month_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, month_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(year_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, year_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(src_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, src_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(day_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, day_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(month_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, month_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(year_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, year_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof PicTimeline.Pic)) {
        return super.equals(obj);
      }
      PicTimeline.Pic other = (PicTimeline.Pic) obj;

      if (!getSrc()
              .equals(other.getSrc())) return false;
      if (!getDay()
              .equals(other.getDay())) return false;
      if (!getMonth()
              .equals(other.getMonth())) return false;
      if (!getYear()
              .equals(other.getYear())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SRC_FIELD_NUMBER;
      hash = (53 * hash) + getSrc().hashCode();
      hash = (37 * hash) + DAY_FIELD_NUMBER;
      hash = (53 * hash) + getDay().hashCode();
      hash = (37 * hash) + MONTH_FIELD_NUMBER;
      hash = (53 * hash) + getMonth().hashCode();
      hash = (37 * hash) + YEAR_FIELD_NUMBER;
      hash = (53 * hash) + getYear().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PicTimeline.Pic parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static PicTimeline.Pic parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static PicTimeline.Pic parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static PicTimeline.Pic parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static PicTimeline.Pic parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static PicTimeline.Pic parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static PicTimeline.Pic parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }

    public static PicTimeline.Pic parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static PicTimeline.Pic parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }

    public static PicTimeline.Pic parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static PicTimeline.Pic parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }

    public static PicTimeline.Pic parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(PicTimeline.Pic prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * Protobuf type {@code Pic}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:Pic)
            PicTimeline.PicOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return PicTimeline.internal_static_Pic_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return PicTimeline.internal_static_Pic_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        PicTimeline.Pic.class, PicTimeline.Pic.Builder.class);
      }

      // Construct using PicTimeline.Pic.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        src_ = "";

        day_ = "";

        month_ = "";

        year_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return PicTimeline.internal_static_Pic_descriptor;
      }

      @java.lang.Override
      public PicTimeline.Pic getDefaultInstanceForType() {
        return PicTimeline.Pic.getDefaultInstance();
      }

      @java.lang.Override
      public PicTimeline.Pic build() {
        PicTimeline.Pic result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public PicTimeline.Pic buildPartial() {
        PicTimeline.Pic result = new PicTimeline.Pic(this);
        result.src_ = src_;
        result.day_ = day_;
        result.month_ = month_;
        result.year_ = year_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }

      @java.lang.Override
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PicTimeline.Pic) {
          return mergeFrom((PicTimeline.Pic) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PicTimeline.Pic other) {
        if (other == PicTimeline.Pic.getDefaultInstance()) return this;
        if (!other.getSrc().isEmpty()) {
          src_ = other.src_;
          onChanged();
        }
        if (!other.getDay().isEmpty()) {
          day_ = other.day_;
          onChanged();
        }
        if (!other.getMonth().isEmpty()) {
          month_ = other.month_;
          onChanged();
        }
        if (!other.getYear().isEmpty()) {
          year_ = other.year_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        PicTimeline.Pic parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PicTimeline.Pic) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object src_ = "";

      /**
       * <code>string src = 1;</code>
       *
       * @return The src.
       */
      public java.lang.String getSrc() {
        java.lang.Object ref = src_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          src_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>string src = 1;</code>
       *
       * @return The bytes for src.
       */
      public com.google.protobuf.ByteString
      getSrcBytes() {
        java.lang.Object ref = src_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          src_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string src = 1;</code>
       *
       * @param value The src to set.
       * @return This builder for chaining.
       */
      public Builder setSrc(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        src_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string src = 1;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearSrc() {

        src_ = getDefaultInstance().getSrc();
        onChanged();
        return this;
      }

      /**
       * <code>string src = 1;</code>
       *
       * @param value The bytes for src to set.
       * @return This builder for chaining.
       */
      public Builder setSrcBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        src_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object day_ = "";

      /**
       * <code>string day = 2;</code>
       *
       * @return The day.
       */
      public java.lang.String getDay() {
        java.lang.Object ref = day_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          day_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>string day = 2;</code>
       *
       * @return The bytes for day.
       */
      public com.google.protobuf.ByteString
      getDayBytes() {
        java.lang.Object ref = day_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          day_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string day = 2;</code>
       *
       * @param value The day to set.
       * @return This builder for chaining.
       */
      public Builder setDay(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        day_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string day = 2;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearDay() {

        day_ = getDefaultInstance().getDay();
        onChanged();
        return this;
      }

      /**
       * <code>string day = 2;</code>
       *
       * @param value The bytes for day to set.
       * @return This builder for chaining.
       */
      public Builder setDayBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        day_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object month_ = "";

      /**
       * <code>string month = 3;</code>
       *
       * @return The month.
       */
      public java.lang.String getMonth() {
        java.lang.Object ref = month_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          month_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>string month = 3;</code>
       *
       * @return The bytes for month.
       */
      public com.google.protobuf.ByteString
      getMonthBytes() {
        java.lang.Object ref = month_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          month_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string month = 3;</code>
       *
       * @param value The month to set.
       * @return This builder for chaining.
       */
      public Builder setMonth(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        month_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string month = 3;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearMonth() {

        month_ = getDefaultInstance().getMonth();
        onChanged();
        return this;
      }

      /**
       * <code>string month = 3;</code>
       *
       * @param value The bytes for month to set.
       * @return This builder for chaining.
       */
      public Builder setMonthBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        month_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object year_ = "";

      /**
       * <code>string year = 4;</code>
       *
       * @return The year.
       */
      public java.lang.String getYear() {
        java.lang.Object ref = year_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          year_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>string year = 4;</code>
       *
       * @return The bytes for year.
       */
      public com.google.protobuf.ByteString
      getYearBytes() {
        java.lang.Object ref = year_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          year_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string year = 4;</code>
       *
       * @param value The year to set.
       * @return This builder for chaining.
       */
      public Builder setYear(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        year_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string year = 4;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearYear() {

        year_ = getDefaultInstance().getYear();
        onChanged();
        return this;
      }

      /**
       * <code>string year = 4;</code>
       *
       * @param value The bytes for year to set.
       * @return This builder for chaining.
       */
      public Builder setYearBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        year_ = value;
        onChanged();
        return this;
      }

      @java.lang.Override
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Pic)
    }

    // @@protoc_insertion_point(class_scope:Pic)
    private static final PicTimeline.Pic DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE = new PicTimeline.Pic();
    }

    public static PicTimeline.Pic getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Pic>
            PARSER = new com.google.protobuf.AbstractParser<Pic>() {
      @java.lang.Override
      public Pic parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return new Pic(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Pic> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Pic> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public PicTimeline.Pic getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_Pics_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_Pics_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_PicsList_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_PicsList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_Pic_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_Pic_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor
          descriptor;

  static {
    java.lang.String[] descriptorData = {
            "\n\021PicTimeline.proto\"1\n\004Pics\022\030\n\005array\030\001 \003" +
                    "(\0132\t.PicsList\022\017\n\007hasNext\030\002 \001(\005\"1\n\010PicsLi" +
                    "st\022\021\n\tdateTitle\030\001 \001(\t\022\022\n\004data\030\002 \003(\0132\004.Pi" +
                    "c\"<\n\003Pic\022\013\n\003src\030\001 \001(\t\022\013\n\003day\030\002 \001(\t\022\r\n\005mo" +
                    "nth\030\003 \001(\t\022\014\n\004year\030\004 \001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[]{
                    });
    internal_static_Pics_descriptor =
            getDescriptor().getMessageTypes().get(0);
    internal_static_Pics_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_Pics_descriptor,
            new java.lang.String[]{"Array", "HasNext",});
    internal_static_PicsList_descriptor =
            getDescriptor().getMessageTypes().get(1);
    internal_static_PicsList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_PicsList_descriptor,
            new java.lang.String[]{"DateTitle", "Data",});
    internal_static_Pic_descriptor =
            getDescriptor().getMessageTypes().get(2);
    internal_static_Pic_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_Pic_descriptor,
            new java.lang.String[]{"Src", "Day", "Month", "Year",});
  }

  // @@protoc_insertion_point(outer_class_scope)
}
